"""create charge_heads quotations and quotation_charge_lines tables

Revision ID: 32df4653e058
Revises: 8aea79ed7c6f
Create Date: 2026-07-18 17:46:37.790655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32df4653e058'
down_revision: Union[str, None] = '8aea79ed7c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_heads',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_heads_code'), 'charge_heads', ['code'], unique=False)
    op.create_index(op.f('ix_charge_heads_tenant_id'), 'charge_heads', ['tenant_id'], unique=False)
    op.create_table('quotations',
    sa.Column('quote_number', sa.String(length=30), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('previous_quote_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=150), nullable=True),
    sa.Column('commodity', sa.String(length=250), nullable=True),
    sa.Column('hs_code', sa.String(length=15), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('container_type_id', sa.UUID(), nullable=True),
    sa.Column('incoterm_id', sa.UUID(), nullable=True),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_terms', sa.String(length=30), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_buy_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_sell_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['container_type_id'], ['container_types.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['previous_quote_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_account_id'), 'quotations', ['account_id'], unique=False)
    op.create_index(op.f('ix_quotations_opportunity_id'), 'quotations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=False)
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_table('quotation_charge_lines',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('charge_head_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('buy_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sell_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sell_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['charge_head_id'], ['charge_heads.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_charge_lines_quotation_id'), 'quotation_charge_lines', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_charge_lines_tenant_id'), 'quotation_charge_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_charge_lines_tenant_id'), table_name='quotation_charge_lines')
    op.drop_index(op.f('ix_quotation_charge_lines_quotation_id'), table_name='quotation_charge_lines')
    op.drop_table('quotation_charge_lines')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_opportunity_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_account_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_charge_heads_tenant_id'), table_name='charge_heads')
    op.drop_index(op.f('ix_charge_heads_code'), table_name='charge_heads')
    op.drop_table('charge_heads')
    # ### end Alembic commands ###