"""create field_permissions table

Revision ID: 5e2a56c40d16
Revises: 7efd4b17660f
Create Date: 2026-07-23 11:14:56.001787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2a56c40d16'
down_revision: Union[str, None] = '7efd4b17660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_permissions_role_id'), 'field_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_field_permissions_tenant_id'), 'field_permissions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_permissions_tenant_id'), table_name='field_permissions')
    op.drop_index(op.f('ix_field_permissions_role_id'), table_name='field_permissions')
    op.drop_table('field_permissions')
    # ### end Alembic commands ###