"""create opportunities table

Revision ID: 8aea79ed7c6f
Revises: 9ec477a8dec7
Create Date: 2026-07-18 17:43:00.738280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aea79ed7c6f'
down_revision: Union[str, None] = '9ec477a8dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('opportunity_name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('probability_pct', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=150), nullable=True),
    sa.Column('commodity', sa.String(length=200), nullable=True),
    sa.Column('hs_code', sa.String(length=15), nullable=True),
    sa.Column('estimated_volume', sa.String(length=100), nullable=True),
    sa.Column('competitors', sa.Text(), nullable=True),
    sa.Column('win_loss_reason', sa.Text(), nullable=True),
    sa.Column('loss_reason_category', sa.String(length=30), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_account_id'), 'opportunities', ['account_id'], unique=False)
    op.create_index(op.f('ix_opportunities_assigned_to_id'), 'opportunities', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_opportunities_tenant_id'), 'opportunities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_tenant_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_assigned_to_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_account_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###