"""create leads table

Revision ID: 9ec477a8dec7
Revises: b2dad4a0e4e0
Create Date: 2026-07-18 17:40:42.519751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec477a8dec7'
down_revision: Union[str, None] = 'b2dad4a0e4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('lead_source', sa.String(length=30), nullable=True),
    sa.Column('lead_status', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('service_interest', sa.String(length=200), nullable=True),
    sa.Column('origin_region', sa.String(length=150), nullable=True),
    sa.Column('destination_region', sa.String(length=150), nullable=True),
    sa.Column('estimated_monthly_volume', sa.String(length=100), nullable=True),
    sa.Column('commodity_type', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('last_contacted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('lead_temperature', sa.String(length=10), nullable=True),
    sa.Column('referral_source_name', sa.String(length=150), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('converted_account_id', sa.UUID(), nullable=True),
    sa.Column('converted_to_opportunity', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['converted_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###