"""create accounts table

Revision ID: bdc247dae836
Revises: 752c59602327
Create Date: 2026-07-18 17:29:53.654467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc247dae836'
down_revision: Union[str, None] = '752c59602327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('iec_code', sa.String(length=10), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=150), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=150), nullable=False),
    sa.Column('primary_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('secondary_contact_name', sa.String(length=150), nullable=True),
    sa.Column('secondary_contact_email', sa.String(length=150), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=30), nullable=True),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('account_rating', sa.String(length=5), nullable=True),
    sa.Column('preferred_currency_id', sa.UUID(), nullable=True),
    sa.Column('preferred_lanes', sa.Text(), nullable=True),
    sa.Column('key_commodities', sa.Text(), nullable=True),
    sa.Column('annual_revenue_potential', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('assigned_account_manager_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_account_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['preferred_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###