"""create remaining masters airport cfs vessel airline uom hscode servicetype leadsource industrytype documenttype quotetnc

Revision ID: e776fa2858fd
Revises: c537bef72a49
Create Date: 2026-07-18 18:06:56.395324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e776fa2858fd'
down_revision: Union[str, None] = 'c537bef72a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_code'), 'airlines', ['code'], unique=False)
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airlines_tenant_id'), 'airlines', ['tenant_id'], unique=False)
    op.create_table('airports',
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=False)
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_tenant_id'), 'airports', ['tenant_id'], unique=False)
    op.create_table('document_types',
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=False)
    op.create_index(op.f('ix_document_types_tenant_id'), 'document_types', ['tenant_id'], unique=False)
    op.create_table('hs_codes',
    sa.Column('duty_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_code'), 'hs_codes', ['code'], unique=False)
    op.create_index(op.f('ix_hs_codes_tenant_id'), 'hs_codes', ['tenant_id'], unique=False)
    op.create_table('industry_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_types_code'), 'industry_types', ['code'], unique=False)
    op.create_index(op.f('ix_industry_types_tenant_id'), 'industry_types', ['tenant_id'], unique=False)
    op.create_table('lead_source_masters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_source_masters_code'), 'lead_source_masters', ['code'], unique=False)
    op.create_index(op.f('ix_lead_source_masters_tenant_id'), 'lead_source_masters', ['tenant_id'], unique=False)
    op.create_table('quote_tnc_templates',
    sa.Column('terms_and_conditions', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_tnc_templates_code'), 'quote_tnc_templates', ['code'], unique=False)
    op.create_index(op.f('ix_quote_tnc_templates_tenant_id'), 'quote_tnc_templates', ['tenant_id'], unique=False)
    op.create_table('service_types',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_code'), 'service_types', ['code'], unique=False)
    op.create_index(op.f('ix_service_types_tenant_id'), 'service_types', ['tenant_id'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('decimal_precision', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_of_measure_code'), 'units_of_measure', ['code'], unique=False)
    op.create_index(op.f('ix_units_of_measure_tenant_id'), 'units_of_measure', ['tenant_id'], unique=False)
    op.create_table('vessels',
    sa.Column('imo_number', sa.String(length=7), nullable=False),
    sa.Column('flag_country', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=150), nullable=True),
    sa.Column('vessel_type', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_code'), 'vessels', ['code'], unique=False)
    op.create_index(op.f('ix_vessels_imo_number'), 'vessels', ['imo_number'], unique=False)
    op.create_index(op.f('ix_vessels_tenant_id'), 'vessels', ['tenant_id'], unique=False)
    op.create_table('cfs',
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('port_id', sa.UUID(), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile_no', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfs_code'), 'cfs', ['code'], unique=False)
    op.create_index(op.f('ix_cfs_port_id'), 'cfs', ['port_id'], unique=False)
    op.create_index(op.f('ix_cfs_tenant_id'), 'cfs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfs_tenant_id'), table_name='cfs')
    op.drop_index(op.f('ix_cfs_port_id'), table_name='cfs')
    op.drop_index(op.f('ix_cfs_code'), table_name='cfs')
    op.drop_table('cfs')
    op.drop_index(op.f('ix_vessels_tenant_id'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_imo_number'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_code'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_units_of_measure_tenant_id'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_code'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_service_types_tenant_id'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_code'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index(op.f('ix_quote_tnc_templates_tenant_id'), table_name='quote_tnc_templates')
    op.drop_index(op.f('ix_quote_tnc_templates_code'), table_name='quote_tnc_templates')
    op.drop_table('quote_tnc_templates')
    op.drop_index(op.f('ix_lead_source_masters_tenant_id'), table_name='lead_source_masters')
    op.drop_index(op.f('ix_lead_source_masters_code'), table_name='lead_source_masters')
    op.drop_table('lead_source_masters')
    op.drop_index(op.f('ix_industry_types_tenant_id'), table_name='industry_types')
    op.drop_index(op.f('ix_industry_types_code'), table_name='industry_types')
    op.drop_table('industry_types')
    op.drop_index(op.f('ix_hs_codes_tenant_id'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_code'), table_name='hs_codes')
    op.drop_table('hs_codes')
    op.drop_index(op.f('ix_document_types_tenant_id'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_airports_tenant_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_tenant_id'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###