from app.models.tenant import Tenant                              # noqa: F401
from app.models.role import Role                                  # noqa: F401
from app.models.user import User                                   # noqa: F401
from app.models.port import Port                                   # noqa: F401
from app.models.currency import Currency                           # noqa: F401
from app.models.incoterm import Incoterm                           # noqa: F401
from app.models.container_type import ContainerType                # noqa: F401
from app.models.account import Account                              # noqa: F401
from app.models.contact import Contact                              # noqa: F401
from app.models.lead import Lead                                    # noqa: F401
from app.models.opportunity import Opportunity                     # noqa: F401
from app.models.charge_head import ChargeHead                      # noqa: F401
from app.models.quotation import Quotation                         # noqa: F401
from app.models.quotation_charge_line import QuotationChargeLine   # noqa: F401
from app.models.activity import Activity                            # noqa: F401
from app.models.airport import Airport                              # noqa: F401
from app.models.cfs import CFS                                      # noqa: F401
from app.models.vessel import Vessel                                # noqa: F401
from app.models.airline import Airline                              # noqa: F401
from app.models.unit_of_measure import UnitOfMeasure                # noqa: F401
from app.models.hs_code import HSCode                                # noqa: F401
from app.models.service_type import ServiceType                     # noqa: F401
from app.models.lead_source import LeadSourceMaster                 # noqa: F401
from app.models.industry_type import IndustryType                   # noqa: F401
from app.models.document_type import DocumentType                   # noqa: F401
from app.models.quote_tnc_template import QuoteTncTemplate           # noqa: F401
from app.models.permission import Permission  # noqa: F401
from app.models.super_admin import SuperAdmin  # noqa: F401
from app.models.notification import Notification  # noqa: F401
from app.models.document import Document  # noqa: F401
from app.models.field_permission import FieldPermission  # noqa: F401